name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Authenticate with ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 211125646202.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t wisecow-app:latest .
        docker tag wisecow-app:latest 211125646202.dkr.ecr.us-east-1.amazonaws.com/wisecow-app:latest
        docker push 211125646202.dkr.ecr.us-east-1.amazonaws.com/wisecow-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Authenticate with Kubernetes
      run: |
        aws eks update-kubeconfig --region us-east-1 --name wisecow-cluster

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
