apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow-app
  ports:
    - protocol: TCP
      port: 80           # External port (what users will use to access the app)
      targetPort: 4499    # Internal container port
  type: LoadBalancer
